---
- name: Validate role variables.
  ansible.builtin.import_tasks: assert.yml
  tags:
    - always

- name: "Debug: OS version."
  ansible.builtin.debug:
    var: ansible_facts.distribution_major_version
    verbosity: 1

- name: "Debug: OS name."
  ansible.builtin.debug:
    var: ansible_facts.distribution
    verbosity: 1

# Install monitoring script
# Monitoring Memory and Disk Metrics for Amazon EC2 Linux Instances
# See: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/mon-scripts.html

- name: Install script dependencies for EL (any).
  ansible.builtin.package:
    name: "{{ package_dependencies }}"
    state: present
  when:
    - ansible_facts.distribution == 'CentOS' or ansible_facts.distribution == 'RedHat'

- name: Install script dependencies for EL 7.
  ansible.builtin.package:
    name:
      - perl-Sys-Syslog
      - perl-LWP-Protocol-https
    state: present
  when:
    - ansible_facts.distribution == 'CentOS' or ansible_facts.distribution == 'RedHat'
    - ansible_facts.distribution_major_version == '7'

- name: Unarchive the CloudWatch monitoring package.
  ansible.builtin.unarchive:
    src: "{{ aws_mon_script_url }}"
    dest: "{{ aws_mon_script_install_dir }}"
    remote_src: true
    mode: "0755"
  register: get_mon_script

- name: "Debug: monitoring script install."
  ansible.builtin.debug:
    var: get_mon_script
    verbosity: 2

- name: Set a cron every 5 minutes to run perl.
  ansible.builtin.cron:
    name: "run mon-put-instance-data.pl every 5mn"
    minute: "*/5"
    user: root
    job: >
      {{ aws_mon_script_install_dir }}/aws-scripts-mon/mon-put-instance-data.pl --mem-used --swap-util
      --mem-util --mem-used --mem-avail --disk-space-util --disk-path=/ --from-cron
    cron_file: ansible_aws_mon-put-instance-data
